"""Generate docs/TOOLS.md from the live registry.

    python scripts/tools_catalogue.py --write

An MCP client or the agent itself receives all of this at handshake; the file
exists so a human can browse the surface without starting a session.
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "src"))

from claudephone.agent import OUTBOUND, build_registry  # noqa: E402

PACK_BLURBS = {
    "core": "Loaded by default. Enough to orient on any screen and find more tools.",
    "system": "Device state: battery, network, storage, notifications, waiting.",
    "shell": "Arbitrary commands at both privilege levels, plus Python evaluation.",
    "files": "Read, write, search and move files across both filesystems.",
    "phone": "The phone as a phone: radios, sensors, camera, telephony, TTS.",
    "learn": "Teach the agent a new app: explore a screen, diff it, save selectors.",
    "instagram": "Instagram profiles, grids, reels and comment threads.",
    "instagram_capture": "Segmented screen recording of reels via MediaProjection.",
    "instagram_web": "Instagram over HTTP, no device - far faster where it works.",
    "x": "X/Twitter timelines, search, and the feed-shaping controls.",
}


def render() -> str:
    reg = build_registry()
    by_pack: dict[str, list] = {}
    for t in reg.tools.values():
        by_pack.setdefault(t.pack, []).append(t)

    out = [
        "# Tool catalogue",
        "",
        "Generated by `python scripts/tools_catalogue.py --write` - do not edit "
        "by hand.",
        "",
        "**" + str(len(reg.tools)) + " tools** in **" + str(len(by_pack))
        + " packs**. Only `core` is loaded at the start of a run; the agent "
        "widens its own surface with `use_tools(pack)`. See "
        "[ARCHITECTURE.md](ARCHITECTURE.md#packs) for why.",
        "",
        "`!` marks a tool that changes device state or reaches the outside "
        "world. Those are gated by the permission policy (`--mode ask` "
        "prompts, `--mode readonly` blocks).",
        "",
    ]

    order = ["core"] + sorted(p for p in by_pack if p != "core")
    out.append("| Pack | Tools | Loaded by default | What it is for |")
    out.append("|---|---|---|---|")
    for p in order:
        out.append("| `" + p + "` | " + str(len(by_pack[p])) + " | "
                   + ("yes" if p in reg.active_packs else "no") + " | "
                   + PACK_BLURBS.get(p, "") + " |")
    out.append("")

    for p in order:
        out.append("## " + p)
        out.append("")
        if PACK_BLURBS.get(p):
            out.append(PACK_BLURBS[p])
            out.append("")
        out.append("| Tool | Arguments | Description |")
        out.append("|---|---|---|")
        for t in sorted(by_pack[p], key=lambda x: x.name):
            props = (t.schema.get("properties") or {})
            req = set(t.schema.get("required") or [])
            args = ", ".join(k + ("" if k in req else "?") for k in props)
            desc = " ".join(t.description.split())
            desc = desc.split(". ")[0].rstrip(".")
            flag = " !" if (t.dangerous or t.name in OUTBOUND) else ""
            out.append("| `" + t.name + "`" + flag + " | `(" + args + ")` | "
                       + desc.replace("|", "\\|") + " |")
        out.append("")

    out.append("---")
    out.append("")
    out.append("`?` marks an optional argument. Descriptions here are the first "
               "sentence only; the agent receives the full text.")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    text = render()
    if a.write:
        dest = os.path.join(os.path.dirname(os.path.dirname(
            os.path.abspath(__file__))), "docs", "TOOLS.md")
        with open(dest, "w", encoding="utf-8") as f:
            f.write(text)
        print("wrote " + dest)
    else:
        print(text)
